<h4>Summary</h4>  
<blockquote>  
    Promise <br>
</blockquote>  

- <h4>Promise</h4>  
    先前也有写过,不过感觉有些问题,现在是重新写.
    Reference:  
    >  [Promise A+标准 Github](https://github.com/promises-aplus/promises-spec)  
    [Hackernoon - implement javascript promise in 70 lines](https://hackernoon.com/implementing-javascript-promise-in-70-lines-of-code-b3592565af0f)


    promise是一个有then方法的对象,它有state和value属性.  
    state有三种可能:'pending','fulfilled'和'rejected'.  
    其中promise处于'pending',那么它的状态还是可修改的,但是一旦处于其它两种状态后,它的state和value就是不可修改的了.  
    promise的构造函数接受一个function作为参数,这个function被称为executor.executor接受两个参数,一个是resolve方法,另一个是reject方法.这两个方法都是用来修改promise的state和value的.  
    promise的then方法是promise能够链式传播的关键,原因是then方法的返回值同样会是一个promise对象.  
    then方法有两个参数,分别是onFulfilled函数和onRejected函数.当promise的状态为'fulfilled'时,onFulfilled函数就会被调用,其中,把promise的value作为onFulfilled的参数.当promise的状态为'rejected'时,onRejected的时候,onRejected就会被调用,value同样是它的参数.如果promise的状态是'rejected',但是又没有传入onRejected来处理这个错误,那么就会把这个promise直接返回,直到被处理.因此,我们也可以通过调用catch方法来捕捉上方promise的error.通常来说,也是通过忽略onRejected机制,使用catch来捕捉错误的.catch同样会返回一个promise的对象,这样一来,promise的链就可以继续了.  
    Hacknoon实现一个promise例子:  
    ```javascript  
        const states = {
        pending: 'Pending',
        resolved: 'Resolved',
        rejected: 'Rejected'
        };

        class Nancy {
        constructor(executor) {
            const tryCall = callback => Nancy.try(() => callback(this.value));
            const laterCalls = [];
            const callLater = getMember => callback => new Nancy(resolve => laterCalls.push(() => resolve(getMember()(callback))));
            const members = {
                [states.resolved]: {
                    state: states.resolved,
                    then: tryCall,
                    catch: _ => this
                },
                [states.rejected]: {
                    state: states.rejected,
                    then: _ => this,
                    catch: tryCall
                },
                [states.pending]: {
                    state: states.pending,
                    then: callLater(() => this.then),
                    catch: callLater(() => this.catch)
                }
            };
            const changeState = state => Object.assign(this, members[state]);
            const apply = (value, state) => {
                if (this.state === states.pending) {
                    this.value = value;
                    changeState(state);
                    for (const laterCall of laterCalls) {
                        laterCall();
                    }
                }
            };

            const getCallback = state => value => {
                if (value instanceof Nancy && state === states.resolved) {
                    value.then(value => apply(value, states.resolved));
                    value.catch(value => apply(value, states.rejected));
                } else {
                    apply(value, state);
                }
            };

            const resolve = getCallback(states.resolved);
            const reject = getCallback(states.rejected);
            changeState(states.pending);
            try {
                executor(resolve, reject);
            } catch (error) {
                reject(error);
            }
        }

        static resolve(value) {
            return new Nancy(resolve => resolve(value));
        }

        static reject(value) {
            return new Nancy((_, reject) => reject(value));
        }

        static try(callback) {
            return new Nancy(resolve => resolve(callback()));
        }
    }
    ```